### ISSUE TITLE
[FEAT] 게시글 Create 기능 서버 연동 구현 

### ISSUE THREAD

**Issue by jane1choi** [Team-Vegin/Vegin-iOS#13]
## 💡 Issue
- 식단 기록 페이지에서 저장하기 버튼을 누르면 서버에 이미지 데이터가 전달되도록 기능 구현합니다.
- 테스트 버전 시연을 위해 식단 기록 시 캘린더의 해당 날짜에 아이콘을 생성하는 기능을 구현합니다.
## 📝  todo 
<!— 해야 할 일들을 적어주세요. —>
- [x] Firebase Storage 파일 추가
- [x] Storage에 이미지 업로드
- [x] 식단 기록 시 캘린더 해당 날짜에 아이콘 생성
