### ISSUE TITLE
✨ [FEAT] 식단 목록 뷰 UI 구성

### ISSUE THREAD

**Issue by jane1choi** [Team-Vegin/Vegin-iOS#21]
## 🥑 Feature Issue
- 식단 목록 뷰의 UI를 구성합니다.

## 🥑 작업 브랜치
- feature/#21-UI-Write-List

## 📝 To-do
- [ ] 상단 캘린더 커스텀
- [ ] 테이블 뷰 구성
- [ ] 플로팅 버튼 배치
- [ ] 플로팅 버튼 클릭 시 기록 뷰로 이동
