### ISSUE TITLE
✨ [FEAT] HomeTab 메인뷰 UI 구성

### ISSUE THREAD

**Issue by tori0403** [Team-Vegin/Vegin-iOS#24]
## 🥑 Feature Issue
- HomeTab의 메인뷰 UI를 구성합니다

## 🥑 작업 브랜치
- feature/#24-UI-Home-MainView

## 📝 To-do
- [x] 버튼 및 이미지 위치 맞추기
- [x] 배경 작물 asset 설정
- [x] characterPageBtn 화면 연결
