### ISSUE TITLE
[FEAT] 식단 기록 뷰 UI 구성

### ISSUE THREAD

**Issue by jane1choi** [Team-Vegin/Vegin-iOS#3]
## 📌  Feature Issue

식단 기록 뷰 UI 구현하기
## 📝  To-do

- [X] 스크롤뷰 구현 
- [x] `NavigationBar`구현
- [X] 전체 화면 UI 구현
- [x] 아이콘 토글 기능 구현
- [x] 화면 전환 구현

## 🔥 Challenging
- [x] 키보드 처리
- [x] 커스텀 팝업 만들기
