### ISSUE TITLE
✨ [FEAT] 캐릭터 도감 UI 구성

### ISSUE THREAD

**Issue by tori0403** [Team-Vegin/Vegin-iOS#38]
## 🥑 Feature Issue
홈 탭의 캐릭터 도감 페이지 UI를 구성합니다.

## 🥑 작업 브랜치
- 브랜치 생성 전

## 📝 To-do
- [x] collectionView 공부하기
- [x] xib CVC 구성하기
- [ ] Carousel 이용해서 CV 구현하기
- [ ] 와이어프레임에 맞게 화면전환 연결하기
