### ISSUE TITLE
✨ [FEAT] 피드 탭 게시글 작성 뷰 UI 구현

### ISSUE THREAD

**Issue by tori0403** [Team-Vegin/Vegin-iOS#46]
## 🥑 Feature Issue
피드 탭의 게시글 작성 뷰 UI를 구현합니다.

## 🥑 작업 브랜치
- #24

## 📝 To-do
- [x] 기존 식단 작성 뷰 코드 확인
- [x] 게시글 작성 뷰에 적용
- [x] 기초 UI 구현
- [x] 이미지 등록 기능 구현
- [x] 텍스트 입력 기능 + 키보드 숨김
- [x] 버튼 비활성화 , 활성화 기능 구현 
- [x] 카테고리 설정 기능 구현
- [x] 입력 완료 후 저장 기능 구현
