### ISSUE TITLE
[ADD] 식단 기록 뷰 디테일 기능 추가 및 탭 별 디폴트 UI 삽입

### ISSUE THREAD

**Issue by jane1choi** [Team-Vegin/Vegin-iOS#8]
## 💡 Issue
식단 기록 뷰에 디테일한 기능을 추가하고 테스트 버전 시안을 위한 디폴트 UI를 삽입합니다.

## 📝  todo 
- [x] 기획 수정에 따른 커스텀 팝업창 UI 수정
- [x] 텍스트 뷰 키보드 관련 기능 추가
- [x] 탭 별 디폴트 UI 삽입
- [x] 식단 기록 페이지 이동 시 탭 바 숨김 기능
