### ISSUE TITLE
realm 기반 DB 구축 및 이미지 crud 테스트

### ISSUE THREAD

**Issue by tori0403** [Team-Vegin/Vegin-iOS#9]
## 💡 Issue
realm 기반 데이터베이스를 구축하고 이미지 crud를 구현, 테스트를 진행합니다.

## 📝  todo 
<!— 해야 할 일들을 적어주세요. —>
- [ ] realm 데이터베이스 구축
- [ ] 어플과 데이터베이스 연동
- [ ] 이미지 crud 개별 프로젝트에 진행
- [ ] 이미지 curd 어플에 적용
- [ ] 이미지 crud 테스트 실행
